name: example
description: An example application using toggle switch widget.
version: 2.2.0
publish_to: none

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  toggle_switch:
    path: ../

  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true