name: toggle_switch
description: Toggle Switch - A simple toggle switch widget. It can be fully customized with desired icons, width, colors, text, corner radius etc. It also maintains selection state.
version: 2.2.1
homepage: https://github.com/PramodJoshi/toggle_switch

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

funding:
  - https://buymeacoffee.com/pramodjoshi

screenshots:
  - description: 'This screenshot shows different examples of Toggle Switch widget.'
    path: screenshots/screenshot1.png
  - description: 'This screenshot shows different examples of Toggle Switch widget.'
    path: screenshots/screenshot2.png
  - description: 'This screenshot shows different examples of Toggle Switch widget.'
    path: screenshots/screenshot3.png

topics:
  - ui
  - toggle
  - switch
  - toggle-switch
  - widget

flutter:
